/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Sesiones */
        get: operations["listar_sesiones_api_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revocar Sesion */
        delete: operations["revocar_sesion_api_v1_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Forgot
         * @description Responde SIEMPRE lo mismo, exista o no la cuenta.
         *
         *     Una respuesta distinta convertiría este endpoint en un verificador de qué
         *     correos están registrados.
         */
        post: operations["password_forgot_api_v1_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset */
        post: operations["password_reset_api_v1_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Usuario, empresa y permisos efectivos.
         *
         *     El frontend usa `permisos` para ADAPTAR la interfaz, nunca para autorizar:
         *     el backend vuelve a verificar en cada request.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transicionar */
        post: operations["transicionar_api_v1_shipments__shipment_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abrir Requisito */
        post: operations["abrir_requisito_api_v1_shipments__shipment_id__requirements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/requirements/{requirement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolver Requisito */
        patch: operations["resolver_requisito_api_v1_shipments__shipment_id__requirements__requirement_id__patch"];
        trace?: never;
    };
    "/api/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Shipments
         * @description Listado con filtros y paginación por cursor.
         *
         *     El `limit` se recorta al máximo del servidor en vez de rechazarse: pedir
         *     10000 devuelve 100, no un error.
         */
        get: operations["listar_shipments_api_v1_shipments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Shipment */
        get: operations["obtener_shipment_api_v1_shipments__shipment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Timeline */
        get: operations["obtener_timeline_api_v1_shipments__shipment_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Cliente
         * @description Vista del cliente.
         *
         *     "Requieren acción" cuenta solo lo que le toca al cliente: un packing list
         *     pendiente es de Operaciones y no debe aparecer aquí (ADR-0003).
         */
        get: operations["dashboard_cliente_api_v1_dashboard_client_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Operaciones
         * @description Vista de Operaciones: cuenta todo lo pendiente, sea de quien sea.
         */
        get: operations["dashboard_operaciones_api_v1_dashboard_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClientType
         * @enum {string}
         */
        ClientType: "WEB" | "IOS" | "ANDROID";
        /** DashboardResponse */
        DashboardResponse: {
            tarjetas: components["schemas"]["TarjetasResponse"];
            /** Proximos Movimientos */
            proximos_movimientos: components["schemas"]["ShipmentResumenResponse"][];
        };
        /** EmpresaResponse */
        EmpresaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Legal Name */
            legal_name: string;
            /** Trade Name */
            trade_name: string | null;
        };
        /** EventoResponse */
        EventoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Event Type */
            event_type: string;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Location */
            location: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Actor */
            actor: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** @default WEB */
            client_type: components["schemas"]["ClientType"];
            /** Device Name */
            device_name?: string | null;
        };
        /**
         * MeResponse
         * @description Lo que el frontend usa para ADAPTAR la interfaz, nunca para autorizar.
         *
         *     Que un permiso no esté en esta lista solo significa que el botón se oculta.
         *     El backend vuelve a verificar en cada request.
         */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            empresa: components["schemas"]["EmpresaResponse"] | null;
            /** Permisos */
            permisos: string[];
        };
        /** MensajeResponse */
        MensajeResponse: {
            /** Mensaje */
            mensaje: string;
        };
        /** PaginaShipments */
        PaginaShipments: {
            /** Items */
            items: components["schemas"]["ShipmentResumenResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** PaginaTimeline */
        PaginaTimeline: {
            /** Items */
            items: components["schemas"]["EventoResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** PasswordForgotRequest */
        PasswordForgotRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** Token */
            token: string;
            /** Nueva Password */
            nueva_password: string;
        };
        /** RequirementPatch */
        RequirementPatch: {
            status: components["schemas"]["RequirementStatus"];
            /** Reason */
            reason?: string | null;
        };
        /** RequirementRequest */
        RequirementRequest: {
            requirement_type: components["schemas"]["RequirementType"];
            /** Title */
            title: string;
            /** Required From */
            required_from: string;
            /** Document Type Id */
            document_type_id?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Blocks Dispatch
             * @default true
             */
            blocks_dispatch: boolean;
            /** Due At */
            due_at?: string | null;
        };
        /** RequirementResponse */
        RequirementResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Shipment Id
             * Format: uuid
             */
            shipment_id: string;
            /** Status */
            status: string;
        };
        /**
         * RequirementStatus
         * @description Dos juegos de estados según el tipo (ADR-0003).
         *
         *     Los documentales tienen ciclo propio porque subir un archivo no equivale a
         *     que Operaciones lo haya aceptado: `UPLOADED` no satisface el requisito,
         *     `VERIFIED` sí.
         * @enum {string}
         */
        RequirementStatus: "OPEN" | "FULFILLED" | "PENDING" | "UPLOADED" | "VERIFIED" | "REJECTED" | "NOT_APPLICABLE" | "WAIVED" | "CANCELLED";
        /**
         * RequirementType
         * @enum {string}
         */
        RequirementType: "DOCUMENT" | "INFORMATION" | "PAYMENT" | "ACTION";
        /** SessionResponse */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Type */
            client_type: string;
            /** Device Name */
            device_name: string | null;
            /** Ip Last Used */
            ip_last_used: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Used At
             * Format: date-time
             */
            last_used_at: string;
            /** Es Sesion Actual */
            es_sesion_actual: boolean;
        };
        /** ShipmentDetalleResponse */
        ShipmentDetalleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Shipment Number */
            shipment_number: string;
            /** Status */
            status: string;
            /** Open Requirements Count */
            open_requirements_count: number;
            /** Client Action Required Count */
            client_action_required_count: number;
            /** Invoice */
            invoice: string | null;
            origin: components["schemas"]["UbicacionResponse"];
            destination: components["schemas"]["UbicacionResponse"];
            /** Estimated Arrival At */
            estimated_arrival_at: string | null;
            /** Current Location */
            current_location: string | null;
            /** Transport Mode */
            transport_mode: string | null;
            /** Package Count */
            package_count: number;
            /** Permit Review Required */
            permit_review_required: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Row Version */
            row_version: number;
            /** Description */
            description: string | null;
            /** Destination Address */
            destination_address: string | null;
            /** Received At */
            received_at: string | null;
            /** Stored At */
            stored_at: string | null;
            /** Dispatched At */
            dispatched_at: string | null;
            /** Delivered At */
            delivered_at: string | null;
        };
        /**
         * ShipmentResumenResponse
         * @description Resumen de carga para listados y dashboard.
         *
         *     `status` y `open_requirements_count` son campos SEPARADOS a propósito:
         *     "faltan documentos" no reemplaza al estado logístico. La carga puede estar
         *     `IN_TRANSIT` con requisitos abiertos, y la interfaz muestra las dos cosas.
         */
        ShipmentResumenResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Shipment Number */
            shipment_number: string;
            /** Status */
            status: string;
            /** Open Requirements Count */
            open_requirements_count: number;
            /** Client Action Required Count */
            client_action_required_count: number;
            /** Invoice */
            invoice: string | null;
            origin: components["schemas"]["UbicacionResponse"];
            destination: components["schemas"]["UbicacionResponse"];
            /** Estimated Arrival At */
            estimated_arrival_at: string | null;
            /** Current Location */
            current_location: string | null;
            /** Transport Mode */
            transport_mode: string | null;
            /** Package Count */
            package_count: number;
            /** Permit Review Required */
            permit_review_required: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ShipmentStatus
         * @description Catálogo de ADR-0001. Los valores viven en base; este enum es para que
         *     el código no use strings sueltos.
         * @enum {string}
         */
        ShipmentStatus: "PRE_ALERT" | "IN_TRANSIT" | "RECEIVED" | "STORED" | "DISPATCH_REQUESTED" | "PREPARING" | "DISPATCHED" | "DELIVERED" | "CANCELLED";
        /** TarjetasResponse */
        TarjetasResponse: {
            /** En Bodega */
            en_bodega: number;
            /** En Transito */
            en_transito: number;
            /** Proximos A Llegar */
            proximos_a_llegar: number;
            /** Requieren Accion */
            requieren_accion: number;
            /** Entregados Este Mes */
            entregados_este_mes: number;
        };
        /**
         * TokenResponse
         * @description El refresh NO viaja aquí: va en cookie HttpOnly.
         *
         *     Devolverlo en el cuerpo lo dejaría accesible a JavaScript, que es
         *     exactamente lo que la cookie HttpOnly evita.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** TransitionRequest */
        TransitionRequest: {
            to_status: components["schemas"]["ShipmentStatus"];
            /** Row Version */
            row_version: number;
            /** Occurred At */
            occurred_at?: string | null;
            /** Note */
            note?: string | null;
            /** Location */
            location?: string | null;
        };
        /** TransitionResponse */
        TransitionResponse: {
            /**
             * Shipment Id
             * Format: uuid
             */
            shipment_id: string;
            /** From Status */
            from_status: string;
            /** To Status */
            to_status: string;
            /** Row Version */
            row_version: number;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
        };
        /** UbicacionResponse */
        UbicacionResponse: {
            /** Location Code */
            location_code: string;
            /** Name */
            name: string;
            /** Country Code */
            country_code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
        };
    };
    listar_sesiones_api_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    revocar_sesion_api_v1_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_forgot_api_v1_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordForgotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_api_v1_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    transicionar_api_v1_shipments__shipment_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abrir_requisito_api_v1_shipments__shipment_id__requirements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolver_requisito_api_v1_shipments__shipment_id__requirements__requirement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
                requirement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_shipments_api_v1_shipments_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
                status?: components["schemas"]["ShipmentStatus"][] | null;
                company_id?: string | null;
                eta_from?: string | null;
                eta_to?: string | null;
                q?: string | null;
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaShipments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_shipment_api_v1_shipments__shipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentDetalleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_timeline_api_v1_shipments__shipment_id__timeline_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_cliente_api_v1_dashboard_client_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    dashboard_operaciones_api_v1_dashboard_operations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
}
