"""campos comerciales del sistema viejo y ocultamiento de cargas

El sistema anterior manejaba `shipper`, `carrier`, `foots` (CFTS) y el peso en
libras como campos propios, y eran columnas de su listado. Vuelven a serlo:
metidos dentro de la descripción no se pueden buscar ni ordenar, que es
justamente para lo que se usan.

Kilos y libras se guardan por separado, como en el legacy: quien recibe anota lo
que dice la báscula o el documento, y los dos números no siempre convierten
exacto. Calcular uno del otro inventaría una precisión que nadie midió.

`hidden_at` reemplaza al "eliminar" del sistema viejo. No borra nada: la carga
desaparece de los listados pero conserva documentos, línea de tiempo y auditoría,
y se puede recuperar (ADR-0007). Los índices parciales suman `hidden_at IS NULL`
al predicado para que la consulta que filtra lo oculto pueda seguir usándolos.

Revision ID: d82146036c33
Revises: f28bcab77643
Create Date: 2026-08-25 15:27:56.597327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d82146036c33"
down_revision: str | Sequence[str] | None = "f28bcab77643"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shipments", sa.Column("shipper", sa.String(length=180), nullable=True))
    op.add_column("shipments", sa.Column("carrier", sa.String(length=180), nullable=True))
    op.add_column(
        "shipments", sa.Column("foots_cft", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        "shipments", sa.Column("weight_lb", sa.Numeric(precision=14, scale=3), nullable=True)
    )
    op.add_column(
        "shipments", sa.Column("hidden_at", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column("shipments", sa.Column("hidden_by", sa.UUID(), nullable=True))
    op.add_column("shipments", sa.Column("hidden_reason", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_shipments_hidden_by_users"),
        "shipments",
        "users",
        ["hidden_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_shipments_hidden_by_users"), "shipments", type_="foreignkey")
    op.drop_column("shipments", "hidden_reason")
    op.drop_column("shipments", "hidden_by")
    op.drop_column("shipments", "hidden_at")
    op.drop_column("shipments", "weight_lb")
    op.drop_column("shipments", "foots_cft")
    op.drop_column("shipments", "carrier")
    op.drop_column("shipments", "shipper")
    # ### end Alembic commands ###
