"""requisitos y tipos de documento

Requisitos de carga (sección 3.5) y catálogo de documentos (ADR-0003).

`document_types` se crea en Fase 2, antes que el resto del módulo de
documentos, porque `shipment_requirements.document_type_id` lo necesita. Las
tablas `documents` y `shipment_documents` llegan en Fase 3.

Lo que no se lee en el DDL:

- `shipment_requirements` usa DOS juegos de estados según `requirement_type`
  (ADR-0003): los documentales llevan PENDING/UPLOADED/VERIFIED/REJECTED/
  NOT_APPLICABLE, el resto OPEN/FULFILLED. El CHECK impide que un requisito de
  pago quede en VERIFIED, que no significa nada ahí.
- `NOT_APPLICABLE` ("nunca aplicó") y `WAIVED` ("aplicaba y se exoneró") son
  distintos a propósito: mezclarlos perdería esa diferencia en auditoría.
- `required_from` separa lo pendiente del cliente de lo pendiente de
  Operaciones. El packing list es obligatorio pero lo carga Operaciones, así
  que el cliente no debe verlo como acción suya.

Revision ID: 337d2e12aa48
Revises: 44eefa4e0d2e
Create Date: 2026-08-24 13:13:50.714795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "337d2e12aa48"
down_revision: str | Sequence[str] | None = "44eefa4e0d2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_types",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", postgresql.CITEXT(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provided_by", sa.String(length=16), nullable=False),
        sa.Column("allowed_formats", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("required_before_status", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provided_by IN ('CLIENT', 'STAFF')", name=op.f("ck_document_types_provided_by_valido")
        ),
        sa.CheckConstraint(
            "cardinality(allowed_formats) > 0", name=op.f("ck_document_types_al_menos_un_formato")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_types")),
        sa.UniqueConstraint("code", name=op.f("uq_document_types_code")),
    )
    op.create_table(
        "shipment_requirements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("requirement_type", sa.String(length=24), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("required_from", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blocks_dispatch", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("due_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("completed_by", sa.UUID(), nullable=True),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(requirement_type = 'DOCUMENT' AND status IN   ('PENDING', 'UPLOADED', 'VERIFIED', 'REJECTED', 'NOT_APPLICABLE',    'WAIVED', 'CANCELLED')) OR (requirement_type <> 'DOCUMENT' AND status IN   ('OPEN', 'FULFILLED', 'WAIVED', 'CANCELLED'))",
            name=op.f("ck_shipment_requirements_status_valido_para_el_tipo"),
        ),
        sa.CheckConstraint(
            "required_from IN ('CLIENT', 'STAFF')",
            name=op.f("ck_shipment_requirements_required_from_valido"),
        ),
        sa.CheckConstraint(
            "requirement_type <> 'DOCUMENT' OR document_type_id IS NOT NULL",
            name=op.f("ck_shipment_requirements_documental_exige_tipo"),
        ),
        sa.CheckConstraint(
            "requirement_type IN ('DOCUMENT', 'INFORMATION', 'PAYMENT', 'ACTION')",
            name=op.f("ck_shipment_requirements_requirement_type_valido"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('WAIVED', 'REJECTED') OR resolution_reason IS NOT NULL",
            name=op.f("ck_shipment_requirements_exonerar_o_rechazar_exige_motivo"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
            name=op.f("fk_shipment_requirements_completed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_shipment_requirements_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_shipment_requirements_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_requirements_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_requirements")),
    )
    op.create_index(
        "ix_shipment_requirements_pendientes",
        "shipment_requirements",
        ["shipment_id", "required_from"],
        unique=False,
        postgresql_where=sa.text("status IN ('OPEN', 'PENDING', 'UPLOADED', 'REJECTED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_shipment_requirements_pendientes",
        table_name="shipment_requirements",
        postgresql_where=sa.text("status IN ('OPEN', 'PENDING', 'UPLOADED', 'REJECTED')"),
    )
    op.drop_table("shipment_requirements")
    op.drop_table("document_types")
    # ### end Alembic commands ###
