"""users companies y company_memberships

Tablas de identidad (sección 3.3 del documento de arquitectura + ADR-0011).

Notas de diseño que no son evidentes leyendo solo el DDL:

- `users` no tiene `is_staff`. La autorización sale del rol asignado (Paso 1.4),
  nunca de un flag en el usuario.
- `company_memberships` lleva UNIQUE(user_id), más estricto que el
  UNIQUE(company_id, user_id) del documento de arquitectura: ADR-0011 fija un
  usuario por empresa. Habilitar multi-empresa después = cambiar esta
  restricción, sin migrar datos.
- El personal interno de AMVARMAR no tiene fila en `company_memberships`.
- `companies.created_by` es nullable porque las empresas que llegan del sistema
  legacy (Fase 5) no tienen registrado quién las creó.

Revision ID: ebf59dd9d030
Revises: d62ea549f5a9
Create Date: 2026-08-24 11:32:35.662190

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebf59dd9d030"
down_revision: str | Sequence[str] | None = "d62ea549f5a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("email_verified_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "failed_login_attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("locked_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("password_changed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("authz_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_login_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'DISABLED')",
            name=op.f("ck_users_status_valido"),
        ),
        sa.CheckConstraint("authz_version > 0", name=op.f("ck_users_authz_version_positiva")),
        sa.CheckConstraint(
            "failed_login_attempts >= 0", name=op.f("ck_users_intentos_fallidos_no_negativos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("legal_name", sa.String(length=180), nullable=False),
        sa.Column("trade_name", sa.String(length=180), nullable=True),
        sa.Column("tax_id", postgresql.CITEXT(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')", name=op.f("ck_companies_status_valido")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_companies_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(
        "uq_companies_tax_id_activo",
        "companies",
        ["tax_id"],
        unique=True,
        postgresql_where=sa.text("tax_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "company_memberships",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("joined_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('INVITED', 'ACTIVE', 'SUSPENDED')",
            name=op.f("ck_company_memberships_status_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_memberships_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_company_memberships_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_memberships")),
        sa.UniqueConstraint("user_id", name="uq_company_memberships_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_memberships")
    op.drop_index(
        "uq_companies_tax_id_activo",
        table_name="companies",
        postgresql_where=sa.text("tax_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_table("companies")
    op.drop_table("users")
    # ### end Alembic commands ###
