"""rbac roles permisos y asignaciones

Tablas RBAC (sección 3.3 del documento de arquitectura + ADR-0004).

Decisiones que no se leen en el DDL:

- `roles.allowed_scopes` es un array, no un `scope_type` único como en el
  documento de arquitectura: OPS_AGENT admite GLOBAL o ASSIGNED según el puesto
  de cada persona. El alcance concreto vive en `user_role_assignments`.
- `user_role_assignments` tiene DOS índices únicos parciales, no uno compuesto:
  en PostgreSQL NULL no colisiona con NULL, así que un solo
  UNIQUE(user_id, role_id, company_id) permitiría duplicar asignaciones
  globales del mismo rol al mismo usuario.
- El CHECK `company_id_coherente_con_scope` impide que una asignación
  ORGANIZATION quede sin empresa, o que una GLOBAL apunte a una.

Revision ID: a124aa9f2682
Revises: ebf59dd9d030
Create Date: 2026-08-24 11:40:19.214918

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a124aa9f2682"
down_revision: str | Sequence[str] | None = "ebf59dd9d030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", postgresql.CITEXT(), nullable=False),
        sa.Column("resource", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("allowed_scopes", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allowed_scopes <@ ARRAY['GLOBAL','ORGANIZATION','ASSIGNED','OWN']::varchar[]",
            name=op.f("ck_roles_alcances_validos"),
        ),
        sa.CheckConstraint(
            "cardinality(allowed_scopes) > 0", name=op.f("ck_roles_al_menos_un_alcance")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column(
            "granted_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_role_permissions_granted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_role_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("assigned_by", sa.UUID(), nullable=True),
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(scope_type = 'ORGANIZATION' AND company_id IS NOT NULL) OR (scope_type <> 'ORGANIZATION' AND company_id IS NULL)",
            name=op.f("ck_user_role_assignments_company_id_coherente_con_scope"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('GLOBAL', 'ORGANIZATION', 'ASSIGNED', 'OWN')",
            name=op.f("ck_user_role_assignments_scope_type_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name=op.f("fk_user_role_assignments_assigned_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_user_role_assignments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_user_role_assignments_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_role_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role_assignments")),
    )
    op.create_index(
        "uq_user_role_assignments_company",
        "user_role_assignments",
        ["user_id", "role_id", "company_id"],
        unique=True,
        postgresql_where=sa.text("company_id IS NOT NULL"),
    )
    op.create_index(
        "uq_user_role_assignments_global",
        "user_role_assignments",
        ["user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("company_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_user_role_assignments_global",
        table_name="user_role_assignments",
        postgresql_where=sa.text("company_id IS NULL"),
    )
    op.drop_index(
        "uq_user_role_assignments_company",
        table_name="user_role_assignments",
        postgresql_where=sa.text("company_id IS NOT NULL"),
    )
    op.drop_table("user_role_assignments")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
