"""despachos

Solicitudes de despacho (sección 3.7 + ADR-0013).

La pieza central es el índice único parcial
`uq_active_dispatch_per_shipment ON dispatch_request_shipments (shipment_id)
WHERE released_at IS NULL`: hace imposible que dos solicitudes activas reclamen
la misma carga. El `SELECT ... FOR UPDATE` del servicio da un error claro, pero
la garantía es el índice, que vale aunque alguien inserte por SQL directo.

Al cerrar, rechazar o cancelar se llena `released_at` y la carga vuelve a estar
disponible para otra solicitud.

Crea además la secuencia `dispatch_number_seq` y su función, igual que
`shipment_number`: el correlativo se genera en la base para que valga también
si inserta el migrador legacy.

Revision ID: 62dae444e5c2
Revises: 291dfb45b917
Create Date: 2026-08-25 08:23:18.937475

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "62dae444e5c2"
down_revision: str | Sequence[str] | None = "291dfb45b917"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # La secuencia y la función van primero: `dispatch_requests` las usa como
    # DEFAULT de `dispatch_number`.
    op.execute("CREATE SEQUENCE dispatch_number_seq START WITH 1")
    op.execute("""
        CREATE FUNCTION siguiente_dispatch_number() RETURNS VARCHAR AS $$
        BEGIN
            RETURN 'DSP-' || to_char(now(), 'YYYY') || '-'
                   || lpad(nextval('dispatch_number_seq')::text, 6, '0');
        END;
        $$ LANGUAGE plpgsql;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatch_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "dispatch_number",
            sa.String(length=32),
            server_default=sa.text("siguiente_dispatch_number()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("requested_pickup_date", sa.Date(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column(
            "requested_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('SEA', 'AIR', 'LAND', 'PICKUP')",
            name=op.f("ck_dispatch_requests_method_valido"),
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR rejected_reason IS NOT NULL",
            name=op.f("ck_dispatch_requests_rechazo_exige_motivo"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'PREPARING', 'DISPATCHED', 'COMPLETED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_dispatch_requests_status_valido"),
        ),
        sa.CheckConstraint(
            "row_version > 0", name=op.f("ck_dispatch_requests_row_version_positiva")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_dispatch_requests_approved_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_dispatch_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_dispatch_requests_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatch_requests")),
        sa.UniqueConstraint("dispatch_number", name=op.f("uq_dispatch_requests_dispatch_number")),
    )
    op.create_index(
        "ix_dispatch_requests_empresa_estado",
        "dispatch_requests",
        ["company_id", "status", sa.literal_column("requested_at DESC")],
        unique=False,
    )
    op.create_table(
        "dispatch_documents",
        sa.Column("dispatch_request_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_request_id"],
            ["dispatch_requests.id"],
            name=op.f("fk_dispatch_documents_dispatch_request_id_dispatch_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_dispatch_documents_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_dispatch_documents_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "dispatch_request_id", "document_id", name=op.f("pk_dispatch_documents")
        ),
    )
    op.create_table(
        "dispatch_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("dispatch_request_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_dispatch_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_request_id"],
            ["dispatch_requests.id"],
            name=op.f("fk_dispatch_events_dispatch_request_id_dispatch_requests"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatch_events")),
    )
    op.create_index(
        "ix_dispatch_events_solicitud",
        "dispatch_events",
        ["dispatch_request_id", sa.literal_column("occurred_at DESC"), "id"],
        unique=False,
    )
    op.create_table(
        "dispatch_request_shipments",
        sa.Column("dispatch_request_id", sa.UUID(), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispatch_request_id"],
            ["dispatch_requests.id"],
            name=op.f("fk_dispatch_request_shipments_dispatch_request_id_dispatch_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_dispatch_request_shipments_shipment_id_shipments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "dispatch_request_id", "shipment_id", name=op.f("pk_dispatch_request_shipments")
        ),
    )
    op.create_index(
        "uq_active_dispatch_per_shipment",
        "dispatch_request_shipments",
        ["shipment_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # El DEFAULT depende de la función: hay que soltarlo antes del DROP.
    op.execute("ALTER TABLE dispatch_requests ALTER COLUMN dispatch_number DROP DEFAULT")
    op.execute("DROP FUNCTION IF EXISTS siguiente_dispatch_number()")
    op.execute("DROP SEQUENCE IF EXISTS dispatch_number_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_dispatch_per_shipment",
        table_name="dispatch_request_shipments",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("dispatch_request_shipments")
    op.drop_index("ix_dispatch_events_solicitud", table_name="dispatch_events")
    op.drop_table("dispatch_events")
    op.drop_table("dispatch_documents")
    op.drop_index("ix_dispatch_requests_empresa_estado", table_name="dispatch_requests")
    op.drop_table("dispatch_requests")
    # ### end Alembic commands ###
