"""preferencias de columnas por usuario

El sistema viejo tenía dos tablas —una para administración y otra para
clientes— porque eran dos plantillas distintas. Acá es una sola con la pantalla
como parte de la clave: agregar un listado nuevo no debería obligar a crear otra
tabla.

Revision ID: d98e024bf210
Revises: d82146036c33
Create Date: 2026-08-25 15:42:48.131445

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd98e024bf210'
down_revision: str | Sequence[str] | None = 'd82146036c33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vista', sa.String(length=40), nullable=False),
    sa.Column('columnas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_column_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'vista', name=op.f('pk_column_preferences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_preferences')
    # ### end Alembic commands ###
