"""referencias paquetes y timeline

Identificación, contenido e historia de la carga (sección 3.5).

- `shipment_references`: la factura es la referencia general; el WR es opcional.
  La regla de Miami NO está aquí como CHECK porque depende de
  `facilities.uses_warehouse_receipt`, otra tabla — vive en `policies.py`.
- `shipment_packages`: reemplaza a `PieceWarehouse` del legacy.
- `shipment_events`: append-only, garantizado por TRIGGER, no por convención.
  Un UPDATE o DELETE sobre esta tabla falla aunque venga de una consola de SQL.
  `ON DELETE RESTRICT` sobre el shipment: borrar una carga no puede borrar su
  historia.

Revision ID: 44eefa4e0d2e
Revises: ac24538a8300
Create Date: 2026-08-24 13:04:57.362469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "44eefa4e0d2e"
down_revision: str | Sequence[str] | None = "ac24538a8300"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("from_status_code", sa.String(length=32), nullable=True),
        sa.Column("to_status_code", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=180), nullable=True),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_shipment_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_status_code"],
            ["shipment_statuses.code"],
            name=op.f("fk_shipment_events_from_status_code_shipment_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_events_shipment_id_shipments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_status_code"],
            ["shipment_statuses.code"],
            name=op.f("fk_shipment_events_to_status_code_shipment_statuses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_events")),
    )
    op.create_index(
        "ix_shipment_events_timeline",
        "shipment_events",
        ["shipment_id", sa.literal_column("occurred_at DESC"), "id"],
        unique=False,
    )
    op.create_table(
        "shipment_packages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("package_type", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("length_cm", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("width_cm", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "package_type IN ('PALLET', 'BOX', 'DRUM', 'BUNDLE', 'OTHER')",
            name=op.f("ck_shipment_packages_package_type_valido"),
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm >= 0",
            name=op.f("ck_shipment_packages_alto_no_negativo"),
        ),
        sa.CheckConstraint(
            "length_cm IS NULL OR length_cm >= 0",
            name=op.f("ck_shipment_packages_largo_no_negativo"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_shipment_packages_cantidad_positiva")),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg >= 0",
            name=op.f("ck_shipment_packages_peso_no_negativo"),
        ),
        sa.CheckConstraint(
            "width_cm IS NULL OR width_cm >= 0", name=op.f("ck_shipment_packages_ancho_no_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_packages_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_packages")),
    )
    op.create_index(
        "ix_shipment_packages_shipment", "shipment_packages", ["shipment_id"], unique=False
    )
    op.create_table(
        "shipment_references",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("reference_type", sa.String(length=24), nullable=False),
        sa.Column("value", sa.String(length=180), nullable=False),
        sa.Column("issuer", sa.String(length=180), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reference_type IN ('INVOICE', 'WR', 'PO', 'TRACKING', 'CONTAINER', 'BL', 'OTHER')",
            name=op.f("ck_shipment_references_reference_type_valido"),
        ),
        sa.CheckConstraint(
            "length(btrim(value)) > 0", name=op.f("ck_shipment_references_valor_no_vacio")
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_references_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_references")),
        sa.UniqueConstraint(
            "shipment_id", "reference_type", "value", name="uq_shipment_references_valor"
        ),
    )
    op.create_index(
        "ix_shipment_references_busqueda",
        "shipment_references",
        ["reference_type", "value"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Inmutabilidad de la línea de tiempo, impuesta por la base.
    #
    # Sin este trigger, "append-only" sería una convención que cualquier UPDATE
    # descuidado —o cualquiera con acceso a psql— rompería en silencio. Con él,
    # corregir un error obliga a lo correcto: agregar un evento CORRECTION que
    # explique qué pasó, dejando ambos registros visibles.
    op.execute("""
        CREATE FUNCTION shipment_events_solo_insercion() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'shipment_events es append-only: no se permite % . '
                'Para corregir un evento, inserte uno de tipo CORRECTION.',
                TG_OP
            USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_shipment_events_inmutable
        BEFORE UPDATE OR DELETE ON shipment_events
        FOR EACH ROW EXECUTE FUNCTION shipment_events_solo_insercion();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_shipment_events_inmutable ON shipment_events")
    op.execute("DROP FUNCTION IF EXISTS shipment_events_solo_insercion()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shipment_references_busqueda", table_name="shipment_references")
    op.drop_table("shipment_references")
    op.drop_index("ix_shipment_packages_shipment", table_name="shipment_packages")
    op.drop_table("shipment_packages")
    op.drop_index("ix_shipment_events_timeline", table_name="shipment_events")
    op.drop_table("shipment_events")
    # ### end Alembic commands ###
