"""shipments estados transiciones y ubicaciones

Revision ID: ac24538a8300
Revises: e822495b9f01
Create Date: 2026-08-24 12:36:45.669010

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac24538a8300"
down_revision: str | Sequence[str] | None = "e822495b9f01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("city_code", sa.String(length=10), nullable=False),
        sa.Column("location_code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "country_code = upper(country_code)", name=op.f("ck_locations_country_code_mayusculas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("country_code", "city_code", name="uq_locations_pais_ciudad"),
        sa.UniqueConstraint("location_code", name=op.f("uq_locations_location_code")),
    )
    op.create_table(
        "shipment_statuses",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "category IN ('PRE_ARRIVAL', 'WAREHOUSE', 'DISPATCH', 'FINAL')",
            name=op.f("ck_shipment_statuses_category_valida"),
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_shipment_statuses")),
        sa.UniqueConstraint("sort_order", name=op.f("uq_shipment_statuses_sort_order")),
    )
    op.create_table(
        "facilities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("facility_code", sa.String(length=24), nullable=False),
        sa.Column("facility_type", sa.String(length=24), nullable=False),
        sa.Column(
            "uses_warehouse_receipt", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "facility_type IN ('WAREHOUSE', 'OFFICE', 'PARTNER')",
            name=op.f("ck_facilities_facility_type_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_facilities_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilities")),
        sa.UniqueConstraint("facility_code", name=op.f("uq_facilities_facility_code")),
    )
    op.create_table(
        "shipment_status_transitions",
        sa.Column("from_status_code", sa.String(length=32), nullable=False),
        sa.Column("to_status_code", sa.String(length=32), nullable=False),
        sa.Column("required_permission_id", sa.UUID(), nullable=False),
        sa.Column("requires_reason", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "from_status_code <> to_status_code",
            name=op.f("ck_shipment_status_transitions_estados_distintos"),
        ),
        sa.ForeignKeyConstraint(
            ["from_status_code"],
            ["shipment_statuses.code"],
            name=op.f("fk_shipment_status_transitions_from_status_code_shipment_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["required_permission_id"],
            ["permissions.id"],
            name=op.f("fk_shipment_status_transitions_required_permission_id_permissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_status_code"],
            ["shipment_statuses.code"],
            name=op.f("fk_shipment_status_transitions_to_status_code_shipment_statuses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "from_status_code", "to_status_code", name=op.f("pk_shipment_status_transitions")
        ),
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shipment_number", sa.String(length=32), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("current_status_code", sa.String(length=32), nullable=False),
        sa.Column("transport_mode", sa.String(length=20), nullable=True),
        sa.Column("origin_location_id", sa.UUID(), nullable=False),
        sa.Column("origin_facility_id", sa.UUID(), nullable=True),
        sa.Column("destination_location_id", sa.UUID(), nullable=False),
        sa.Column("destination_address", sa.String(length=240), nullable=True),
        sa.Column("current_location", sa.String(length=180), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("estimated_arrival_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("actual_arrival_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("received_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("stored_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("dispatched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("delivered_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("volumetric_weight_kg", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("volume_m3", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("package_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "permit_review_required", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "legacy_review_required", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("legacy_status", sa.String(length=20), nullable=True),
        sa.Column("retention_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archived_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("legal_hold_reason", sa.Text(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transport_mode IS NULL OR transport_mode IN ('SEA', 'AIR', 'LAND', 'COURIER')",
            name=op.f("ck_shipments_transport_mode_valido"),
        ),
        sa.CheckConstraint(
            "legal_hold = false OR legal_hold_reason IS NOT NULL",
            name=op.f("ck_shipments_legal_hold_exige_motivo"),
        ),
        sa.CheckConstraint("package_count >= 0", name=op.f("ck_shipments_bultos_no_negativos")),
        sa.CheckConstraint("row_version > 0", name=op.f("ck_shipments_row_version_positiva")),
        sa.CheckConstraint(
            "volume_m3 IS NULL OR volume_m3 >= 0", name=op.f("ck_shipments_volumen_no_negativo")
        ),
        sa.CheckConstraint(
            "volumetric_weight_kg IS NULL OR volumetric_weight_kg >= 0",
            name=op.f("ck_shipments_peso_volumetrico_no_negativo"),
        ),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg >= 0", name=op.f("ck_shipments_peso_no_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_shipments_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_shipments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_shipments_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_status_code"],
            ["shipment_statuses.code"],
            name=op.f("fk_shipments_current_status_code_shipment_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
            name=op.f("fk_shipments_destination_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["origin_facility_id"],
            ["facilities.id"],
            name=op.f("fk_shipments_origin_facility_id_facilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
            name=op.f("fk_shipments_origin_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("shipment_number", name=op.f("uq_shipments_shipment_number")),
    )
    op.create_index(
        "ix_shipments_asignado",
        "shipments",
        ["assigned_to", "current_status_code"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.create_index(
        "ix_shipments_empresa_creacion",
        "shipments",
        ["company_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.create_index(
        "ix_shipments_empresa_estado",
        "shipments",
        ["company_id", "current_status_code", sa.literal_column("updated_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.create_index(
        "ix_shipments_empresa_eta",
        "shipments",
        ["company_id", "estimated_arrival_at"],
        unique=False,
        postgresql_where=sa.text(
            "estimated_arrival_at IS NOT NULL AND deleted_at IS NULL AND archived_at IS NULL"
        ),
    )
    op.create_index(
        "ix_shipments_retencion",
        "shipments",
        ["retention_until"],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL AND retention_until IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # Secuencia para el correlativo de shipment_number. `nextval` es atómico:
    # dos transacciones simultáneas nunca obtienen el mismo número, y no se
    # revierte con un rollback (por eso puede haber huecos, que es aceptable —
    # el número es un identificador, no un conteo).
    op.execute("CREATE SEQUENCE shipment_number_seq START WITH 1")

    # La generación vive en la base y no en Python para que el migrador legacy
    # de Fase 5, que inserta por SQL directo, obtenga números del mismo pozo.
    op.execute("""
        CREATE FUNCTION siguiente_shipment_number() RETURNS VARCHAR AS $$
        BEGIN
            RETURN 'SHP-' || to_char(now(), 'YYYY') || '-'
                   || lpad(nextval('shipment_number_seq')::text, 6, '0');
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute(
        "ALTER TABLE shipments ALTER COLUMN shipment_number SET DEFAULT siguiente_shipment_number()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # El DEFAULT depende de la función: hay que soltarlo antes o el DROP falla.
    op.execute("ALTER TABLE shipments ALTER COLUMN shipment_number DROP DEFAULT")
    op.execute("DROP FUNCTION IF EXISTS siguiente_shipment_number()")
    op.execute("DROP SEQUENCE IF EXISTS shipment_number_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_shipments_retencion",
        table_name="shipments",
        postgresql_where=sa.text("archived_at IS NULL AND retention_until IS NOT NULL"),
    )
    op.drop_index(
        "ix_shipments_empresa_eta",
        table_name="shipments",
        postgresql_where=sa.text(
            "estimated_arrival_at IS NOT NULL AND deleted_at IS NULL AND archived_at IS NULL"
        ),
    )
    op.drop_index(
        "ix_shipments_empresa_estado",
        table_name="shipments",
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_index(
        "ix_shipments_empresa_creacion",
        table_name="shipments",
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_index(
        "ix_shipments_asignado",
        table_name="shipments",
        postgresql_where=sa.text("deleted_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_table("shipments")
    op.drop_table("shipment_status_transitions")
    op.drop_table("facilities")
    op.drop_table("shipment_statuses")
    op.drop_table("locations")
    # ### end Alembic commands ###
