"""rastro de la migración legacy

`legacy_id_map` es lo que hace el migrador re-ejecutable: si un registro viejo
ya se migró, la segunda corrida lo reconoce en vez de duplicarlo. La clave del
legacy va como texto porque no siempre es un entero — la carga vieja usa el
`wr_number` de clave primaria.

Revision ID: f28bcab77643
Revises: f6d833ce5fed
Create Date: 2026-08-25 12:05:15.568246

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f28bcab77643"
down_revision: str | Sequence[str] | None = "f6d833ce5fed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_id_map",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("legacy_table", sa.String(length=60), nullable=False),
        sa.Column("legacy_pk", sa.String(length=120), nullable=False),
        sa.Column("new_table", sa.String(length=60), nullable=False),
        sa.Column("new_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "migrated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_id_map")),
    )
    op.create_index(
        "ix_legacy_id_map_destino", "legacy_id_map", ["new_table", "new_uuid"], unique=False
    )
    op.create_index(
        "uq_legacy_id_map_origen", "legacy_id_map", ["legacy_table", "legacy_pk"], unique=True
    )
    op.create_table(
        "legacy_password_pending",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("legacy_algorithm", sa.String(length=40), nullable=False),
        sa.Column(
            "migrated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("converted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_legacy_password_pending_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_legacy_password_pending")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("legacy_password_pending")
    op.drop_index("uq_legacy_id_map_origen", table_name="legacy_id_map")
    op.drop_index("ix_legacy_id_map_destino", table_name="legacy_id_map")
    op.drop_table("legacy_id_map")
    # ### end Alembic commands ###
