"""documentos storage privado y system_settings

Revision ID: 291dfb45b917
Revises: 337d2e12aa48
Create Date: 2026-08-24 23:14:45.150821

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "291dfb45b917"
down_revision: str | Sequence[str] | None = "337d2e12aa48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("key", postgresql.CITEXT(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_secret", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_system_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("storage_provider", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("safe_name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=150), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("upload_status", sa.String(length=20), nullable=False),
        sa.Column("scan_status", sa.String(length=20), nullable=False),
        sa.Column("scanned_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archived_compressed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("original_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "is_digitally_signed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scan_status IN ('PENDING', 'CLEAN', 'INFECTED', 'FAILED')",
            name=op.f("ck_documents_scan_status_valido"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('UPLOADING', 'PROCESSING', 'READY', 'FAILED')",
            name=op.f("ck_documents_upload_status_valido"),
        ),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_documents_sha256_completo")),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_documents_archivo_no_vacio")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_documents_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
    )
    op.create_index(
        "ix_documents_empresa_creacion",
        "documents",
        ["company_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_documents_empresa_hash", "documents", ["company_id", "sha256"], unique=False
    )
    op.create_table(
        "shipment_documents",
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_shipment_documents_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_shipment_documents_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_documents_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("shipment_id", "document_id", name=op.f("pk_shipment_documents")),
    )
    op.create_index(
        "ix_shipment_documents_document", "shipment_documents", ["document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shipment_documents_document", table_name="shipment_documents")
    op.drop_table("shipment_documents")
    op.drop_index("ix_documents_empresa_hash", table_name="documents")
    op.drop_index("ix_documents_empresa_creacion", table_name="documents")
    op.drop_table("documents")
    op.drop_table("system_settings")
    # ### end Alembic commands ###
